---
title: "R Notebook"
output: html_notebook
---

Convert what I plot in python notebook `static graph.ipynb` to R plotly, in order to put into R shiny.

```{r setup, warning=F, message=F}
library(tidyverse)
library(plotly)
```

# 1. The most common aircraft
## get data
```{r message=F, warning=F, result='hide'}
df <- read_csv("/Users/zhengjiexu/Desktop/Study/2.\ Data\ Visualization/4.project/dataviz/operations.csv")
```

```{r}
aircraft <- df %>% select(`Aircraft Series`) %>%
                   filter(is.na(`Aircraft Series`)==F) %>% 
                   group_by(`Aircraft Series`) %>% 
                   summarise('ct' = n()) %>% 
                   arrange(desc(ct)) %>% 
                   top_n(15, ct)
aircraft
```

## plotly
```{r}
xform <- list(categoryorder = "array",
              categoryarray = aircraft$`Aircraft Series`)

p_aircraft <- aircraft %>% plot_ly(x=~`Aircraft Series`, y=~ct, 
                                   type='bar', name="") %>% 
                           layout(title='The moset commmon aricraft', 
                                  yaxis=list(title='Count'), xaxis=xform)
p_aircraft
```


# 2. attacking countries
## get data
```{r}
attack <-  df %>% select(Country) %>% 
                  filter(is.na(Country) == F) %>% 
                  group_by(Country) %>% 
                  summarise('ct' = n()) %>% 
                  arrange(desc(ct))
attack
```

## plotly
```{r}
xform_attack <- list(categoryorder = "array",
                     categoryarray = attack$Country)

p_attack <- attack %>% plot_ly(x=~`Country`, y=~ct, 
                                   type='bar', name="") %>% 
                           layout(title='Attacking Country', 
                                  yaxis=list(title='Count'), xaxis=xform_attack)
p_attack
```

# 3. target country
## get data
```{r}
target <-  df %>% select(`Target Country`) %>% 
                  filter(is.na(`Target Country`) == F) %>% 
                  group_by(`Target Country`) %>% 
                  summarise('ct' = n()) %>% 
                  arrange(desc(ct)) %>% 
                  top_n(15, ct)
target
```

## plotly
```{r}
xform_tar <- list(categoryorder = "array",
                  categoryarray = target$`Target Country`)

p_tar <- target %>% plot_ly(x=~`Target Country`, y=~ct, 
                                   type='bar', name="") %>% 
                           layout(title='Target Country', 
                                  yaxis=list(title='Count'), xaxis=xform_tar)
p_tar
```


# 4. time series
## get data
```{r}
Mission <-  df %>% select(`Mission Date`, `Mission ID`) %>% 
                   filter(is.na(`Mission Date`) == F)

Mission$`Mission Date` <- as.Date(anytime::anydate(Mission$`Mission Date`))
Mission$start_month <- cut(Mission$`Mission Date`, "month") 
Mission$start_month = as.Date(Mission$start_month)
Mission <- Mission %>% arrange(`Mission Date`)
```

```{r}
monthly_ct <- Mission %>% group_by(start_month) %>% 
                          summarise('ct' = n())
monthly_ct
```

## plotly
```{r}
p <- monthly_ct %>% plot_ly(x = ~start_month, y = ~ct, type = 'scatter', mode = 'lines') %>% 
                    layout(title='Monthly count of bomb mission', 
                           yaxis=list(title='Count'), 
                           xaxis=list(title=''))
p
```

